export default {
    START_SEARCHING: 'START_SEARCHING',
    CHANGE_ITEMS: 'CHANGE_ITEMS',
    CHANGE_QUERY: 'CHANGE_QUERY',
    CHANGE_CATEGORY: 'CHANGE_CATEGORY',
    CHANGE_STATUS: 'CHANGE_STATUS',
    CHANGE_TAG: 'CHANGE_TAG',
};
